site_name: Team 5152 Robot Documentation | Reefscape
site_url: https://5152alotobots.github.io/5152_Reefscape/
theme:
  name: material
  palette:
    scheme: slate
    primary: red
    accent: grey
nav:
  - Home: index.md
  - Style Guide: styleguide.md
  - Reefscape:
      - Field Constants: reefscape/fieldconstants.md
      - Subsystems:
          - reefscape/elevator.md
      - Commands:
          - Elevator:
              - Default Elevator Run At Velocity: reefscape/defaultelevatorrunatvelocity.md
              - Elevator Run to Height: reefscape/elevatorruntoheight.md
              - Elevator Open Loop: reefscape/elevatoropenloop.md
  - Library:
      - Commands:
          - Swerve:
              - Default Drive: library/commands/swerve/defaultdrive.md
              - Drive Facing Angle: library/commands/swerve/drivefacingangle.md
              - Drive Facing Pose: library/commands/swerve/drivefacingpose.md
              - Characterization: library/commands/swerve/characterization.md
          - Bling:
              - Set To Alliance Color: library/commands/bling/settoalliancecolor.md
              - No Alliance Waiting: library/commands/bling/noalliancewaiting.md
          - Vision:
              - Object Detection:
                  - Drive Facing Best Object: library/commands/vision/objectdetection/drivefacingbestobject.md
                  - Pathfind to Best Object: library/commands/vision/objectdetection/pathfindtobestobject.md
              - Localization Fusion:
                  - Request Position Reset Via Tags: library/commands/vision/localizationfusion/requestpositionresetviatags.md
              - Oculus QuestNav:
                  - Ping: library/commands/vision/oculus/ping.md
                  - Reset Pose: library/commands/vision/oculus/resetpose.md
                  - Zero Heading: library/commands/vision/oculus/zeroheading.md
      - Subsystems:
          - Swerve: library/subsystems/swerve.md
          - Bling: library/subsystems/bling.md
          - Vision:
              - Object Detection: library/subsystems/vision/objectdetection.md
              - Localization Fusion: library/subsystems/vision/localizationfusion.md
              - AprilTag: library/subsystems/vision/apriltag.md
              - Oculus: library/subsystems/vision/oculus.md
  - Core:
      - CAN IDs: core/canids.md
      - Controller Bindings: core/bindings.md
      - Auto Named Commands: core/autonamedcommands.md
      - Robot: core/robot.md
      - Robot Container: core/robotcontainer.md
      - Constants: core/constants.md
      - Main: core/main.md
      - OI: core/oi.md
  - Quickstart:
      - Swerve Drive: quickstart/swervequickstart.md
      - Vision:
          - AprilTag: quickstart/apriltagquickstart.md
          - Object Detection: quickstart/objectdetectionquickstart.md
          - QuestNav: quickstart/questnavquickstart.md
  - External Documentation:
      - AdvantageKit: https://docs.advantagekit.org/
      - AdvantageScope: https://docs.advantagescope.org/
      - CTRE Phoenix 6: https://v6.docs.ctr-electronics.com/en/stable/
      - PhotonVision: https://docs.photonvision.org/en/latest/
      - WPILib: https://docs.wpilib.org/en/stable/
  - API Documentation: javadoc/index.html

repo_url: https://github.com/5152alotobots/5152_Reefscape
repo_name: 5152Alotobots/5152_Reefscape

markdown_extensions:
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search